### ISSUE TITLE
Plausible-Analytics: Could the secret templating be made optional?

### ISSUE THREAD

**Issue by JimTim** [zekker6/helm-charts#448]
ref: https://github.com/zekker6/helm-charts/blob/main/charts/apps/plausible-analytics/templates/secret.yaml

I use external-secrets on my cluster to generate secrets and this clashes a bit with the fact that this secret is not optional. Could you introduce a key in values.yaml that prevents this secret from being templated? Then I just have to make sure that the required options are included.

Thank you very much.

**Comment by zekker6** [comment]
Please, check out [v0.2.3](https://github.com/zekker6/helm-charts/releases/tag/plausible-analytics-0.2.3) release. It added a parameter to use secret which is managed outside of this chart:
```
# -- Configure an external secret to use for plausible
externalSecret:
  # -- Name of the external secret to use
  name: ""
```
If `.Values.externalSecret.Name` is not empty - it will be used in order to provide env for plausible container instead of default config.

**Comment by JimTim** [comment]
Works! I used the following ExternalSecret:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plausible-analytics
  namespace: plausible
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: <name-of-secret-store>
  target:
    creationPolicy: Owner
    name: plausible
    template:
      metadata:
        labels:
          app.kubernetes.io/name: plausible
  data:
  - secretKey: BASE_URL
    remoteRef:
      key: plausible-analytics
      property: BASE_URL
  - secretKey: ADMIN_USER_EMAIL
    remoteRef:
      key: plausible-analytics
      property: ADMIN_USER_EMAIL
  - secretKey: ADMIN_USER_PWD
    remoteRef:
      key: plausible-analytics
      property: ADMIN_USER_PWD
  - secretKey: ADMIN_USER_NAME
    remoteRef:
      key: plausible-analytics
      property: ADMIN_USER_NAME
  - secretKey: DATABASE_URL
    remoteRef:
      key: plausible-analytics
      property: DATABASE_URL
  - secretKey: CLICKHOUSE_DATABASE_URL
    remoteRef:
      key: plausible-analytics
      property: CLICKHOUSE_DATABASE_URL
  - secretKey: SECRET_KEY_BASE
    remoteRef:
      key: plausible-analytics
      property: SECRET_KEY_BASE
  - secretKey: TOTP_VAULT_KEY
    remoteRef:
      key: plausible-analytics
      property: TOTP_VAULT_KEY
```
