### ISSUE TITLE
Helm install fails for the Readeck chart with error about the common notes

### ISSUE THREAD

**Issue by robinvalk** [zekker6/helm-charts#576]
Hi! 

I'm trying to install Readeck on Kubernetes using your helm chart. The install fails with the following error:

```
Error: INSTALLATION FAILED: template: readeck/templates/NOTES.txt:1:4: executing "readeck/templates/NOTES.txt" at <include "common.notes.defaultNotes" .>: error calling include: template: readeck/charts/common/templates/_notes.tpl:33:16: executing "common.notes.defaultNotes" at <first .paths>: error calling first: runtime error: invalid memory address or nil pointer dereference
```

As it seems to be an issue with the common library I have a couple of questions:

1. Is this chart still supported by you?
2. If not, can you have a quick thought about what should be updated? Maybe I can work on a PR.
3. If yes, can you help me out on how to fix the error? 

I'm impressed with the setup! Looks like a solid base to build support other applications on. Are you open for PRs to add support for other apps?

**Comment by robinvalk** [comment]
Thanks for the quick response. Good to hear it's still maintained and you are open for more apps! 😁 

> Can you share the following details:
> 
> * a chart version you're using

Version 0.6.0

> * values file you're using(with any sensetive details removed)

Hereby the `readeck.values.yaml` I tried the install with
```
#
# IMPORTANT NOTE
#
# This chart inherits from k8s common library chart. You can check the default values/options here:
# https://github.com/zekker6/helm-charts/blob/main/charts/library/common/values.yaml
#

image:
  # -- image repository
  repository: codeberg.org/readeck/readeck
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  # @default -- chart.appVersion
  tag: "0.15.6"

# -- See the following files for additional environment variables:
# https://codeberg.org/readeck/readeck#how-to-test-or-install
# @default -- See below
env:
  READECK_ALLOWED_HOSTS: readeck.k8s.example.org

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: readeck.k8s.example.org
        http:
          paths:
            - path: /
              pathType: Prefix
              service:
                port: http

persistence:
  # -- Configure persistence for data to use sqlite backend.
  # @default -- See values.yaml
  data:
    enabled: true
    mountPath: /readeck
    accessMode: ReadWriteOnce
    size: 512Mi
    emptyDir:
      enabled: false
    storageClass: nfs-config
    retain: true

```

**Comment by zekker6** [comment]
@robinvalk Thank you for sharing! I was able to reproduce an issue and fixed it in https://github.com/zekker6/helm-charts/commit/17d16c31d6475bdbc37d65a4e37d7f62cb7d96ee

The reason for this error is format of the values file which had an extra `http` levle for the `hosts` section. Here is a corrected version to be used for ingress configuration:
```
ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: readeck.k8s.example.org
        paths:
          - path: /
            pathType: Prefix
            service:
              port: http
```

See this for an example as well: https://github.com/zekker6/helm-charts/blob/17d16c31d6475bdbc37d65a4e37d7f62cb7d96ee/charts/library/common/values.yaml#L351-L364

The fix is included in common chart release [v0.5.2](https://github.com/zekker6/helm-charts/releases/tag/common-0.5.2) and readeck chart release [v0.7.0](https://github.com/zekker6/helm-charts/releases/tag/readeck-0.7.0). 
Please try using the latest version and applying an updated configuration for ingress. Let me know if that won't work or if you will have any other questions.

**Comment by robinvalk** [comment]
Wow thanks for the quick fix! The error I got is completely unrelated to the root cause? 😅 Anyhow, I got it working now after I also changed the port reference to an integer and not the port name reference:

```
ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    ingressClassName: traefik
    hosts:
      - host: readeck.k8s.example.org
        paths:
          - path: /
            pathType: Prefix
            service:
              port: 8000
```
