### ISSUE TITLE
Incorrect ingress.hosts[].paths format in values.yaml documentation

### ISSUE THREAD

**Issue by jorgen-k** [zekker6/helm-charts#699]
I encountered an issue while configuring Ingress using this Helm chart. The expected format for ingress.hosts[].paths in Kubernetes normally follows:

```
ingress:
  hosts:
    - host: plausible.staging.agiletto.se
      paths:
        - path: "/"
          pathType: Prefix
```

However, this does not work in this Helm chart. Instead, the following format does work:

```
ingress:
  hosts:
    - host: plausible.staging.agiletto.se
      paths:
        - "/"
```

This behavior is not clearly documented in the values.yaml reference.

Expected Behavior

Either:
	1.	The chart should support the standard Kubernetes Ingress format (where paths should be a list of dictionaries with path and pathType).
	2.	Or, the documentation should explicitly state that paths should be a list of strings, and pathType: Prefix is assumed by default.

Steps to Reproduce
	1.	Use the Helm chart with the “normal” Kubernetes Ingress format (list of dictionaries).
	2.	Deploy the chart.
	3.	Get an error:

_Error: release plausible-analytics failed, and has been uninstalled due to atomic being set: 1 error occurred:
* Ingress.networking.k8s.io "plausible-analytics" is invalid: spec.rules[0].http.paths[0].path: Invalid value: "map[path:/ pathType:Prefix]": must be an absolute path_

	4.	Change the paths value to a list of strings instead of dictionaries.
	5.	Helm deployment succeeds.

Either:
	•	Modify the template to support the standard Ingress format.
	•	Update the documentation to explicitly say:
	“The ingress.hosts[].paths field must be a list of strings, not a list of dictionaries. pathType: Prefix is assumed automatically.”

**Comment by zekker6** [comment]
Hello @jorgen-k , [v0.11.1](https://github.com/zekker6/helm-charts/releases/tag/plausible-analytics-0.11.1) added an ability to specify paths in Kubernetes native format:
```
ingress:
  enabled: true
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
```

It also includes an update to example values to make it easier to find a format of `.hosts` accepted there:
https://github.com/zekker6/helm-charts/blob/36829a59bae6c275fa0f12605b1efb397096259b/charts/apps/plausible-analytics/values.yaml#L156-L160

Please, let me know if that helps.
